version: "3.9"
   
services:
  bot:
    build: .
    container_name: surgaz_bot
    command:  > 
      bash -c "python3 bot.py"
    volumes:
      - .:/code
    ports:
      - "2000:2000"
    env_file:
      - ./.env.local
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

